import { supabase } from './supabase'

const today = () => new Date().toISOString().slice(0, 10)

export function weekStart() {
  const date = new Date()
  date.setDate(date.getDate() - ((date.getDay() + 6) % 7))
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`
}

function sumBy(items, key, amountKey = 'amount') { return items.reduce((totals, item) => ({ ...totals, [item[key]]: (totals[item[key]] || 0) + item[amountKey] }), {}) }
function enrichGoals(goals, logs, userId) { const totals = sumBy(logs, 'goal_id'); const mine = sumBy(logs.filter((log) => log.user_id === userId), 'goal_id'); return goals.map((goal) => ({ ...goal, progress: totals[goal.id] || 0, myProgress: mine[goal.id] || 0 })) }
function enrichChallenges(challenges, participants, logs, userId) { const mine = sumBy(logs.filter((log) => log.user_id === userId), 'challenge_id'); const counts = participants.filter((participant) => participant.status === 'accepted').reduce((totals, participant) => ({ ...totals, [participant.challenge_id]: (totals[participant.challenge_id] || 0) + 1 }), {}); const joined = new Set(participants.filter((participant) => participant.user_id === userId && participant.status === 'accepted').map((participant) => participant.challenge_id)); return challenges.map((challenge) => ({ ...challenge, progress: mine[challenge.id] || 0, participantCount: counts[challenge.id] || 0, joined: joined.has(challenge.id) })) }
function enrichMoments(moments, participants, userId) { const goingCounts = participants.filter((participant) => participant.status === 'going').reduce((totals, participant) => ({ ...totals, [participant.moment_id]: (totals[participant.moment_id] || 0) + 1 }), {}); const responseCounts = participants.reduce((totals, participant) => ({ ...totals, [participant.moment_id]: (totals[participant.moment_id] || 0) + 1 }), {}); const myResponses = new Map(participants.filter((participant) => participant.user_id === userId).map((participant) => [participant.moment_id, participant.status])); return moments.map((moment) => ({ ...moment, participantCount: goingCounts[moment.id] || 0, responseCount: responseCounts[moment.id] || 0, myResponse: myResponses.get(moment.id) || null })) }

export function calculateHarmonyScore(goals, challenges) { const goalScore = goals.reduce((score, goal) => score + (goal.myProgress * 5) + (goal.progress >= goal.target ? (goal.visibility === 'personal' ? 20 : 10) : 0), 0); const challengeScore = challenges.reduce((score, challenge) => score + (challenge.progress * 5) + (challenge.progress >= challenge.target ? 30 : 0), 0); return goalScore + challengeScore }
export function unlockAchievements(goals, challenges, score) { const completed = goals.filter((goal) => goal.progress >= goal.target).length; const shared = goals.filter((goal) => goal.visibility === 'shared' && goal.progress >= goal.target).length; return [completed > 0 && { id: 'first-spark', title: 'First Spark', note: 'Complete your first weekly goal.' }, completed >= 3 && { id: 'steady-hands', title: 'Steady Hands', note: 'Complete three goals in one week.' }, shared > 0 && { id: 'family-fire', title: 'Family Fire', note: 'Help a shared goal reach its target.' }, challenges.some((challenge) => challenge.progress >= challenge.target) && { id: 'friendly-rival', title: 'Friendly Rival', note: 'Finish an opt-in family challenge.' }, score >= 100 && { id: 'bright-week', title: 'Bright Week', note: 'Earn 100 Harmony points.' }].filter(Boolean) }

export async function loadWorkspace(user) {
  const [{ data: profile, error: profileError }, { data: membership, error: membershipError }] = await Promise.all([supabase.from('profiles').select('id, display_name, locale').eq('id', user.id).maybeSingle(), supabase.from('household_members').select('household_id, role').eq('user_id', user.id).limit(1).maybeSingle()])
  if (profileError) throw profileError
  if (membershipError) throw membershipError
  if (!membership) return { profile, membership: null, household: null, checkIns: {}, goals: [], challenges: [], moments: [], memories: [], asks: [], gardenEntries: [], weeklyChoice: null, warmthEvents: [], dailyIntention: null, reflection: null, score: 0, achievements: [] }

  const currentWeek = weekStart()
  const [{ data: household, error: householdError }, { data: checkIns, error: checkInError }, { data: goals, error: goalsError }, { data: reflection, error: reflectionError }, { data: challenges, error: challengesError }, { data: dailyIntention, error: intentionError }, { data: moments, error: momentsError }, { data: memories, error: memoriesError }, { data: asks, error: asksError }, { data: gardenEntries, error: gardenError }, { data: weeklyChoice, error: weeklyChoiceError }, { data: warmthEvents, error: warmthEventError }, { data: profiles, error: profilesError }] = await Promise.all([
    supabase.from('households').select('id, name').eq('id', membership.household_id).single(),
    supabase.from('check_ins').select('kind').eq('user_id', user.id).eq('completed_on', today()),
    supabase.from('weekly_goals').select('id, household_id, created_by, visibility, title, description, target, week_start, created_at, category, preset_key').eq('household_id', membership.household_id).eq('week_start', currentWeek).order('created_at'),
    supabase.from('weekly_reflections').select('id, win, obstacle, next_focus, small_reward').eq('user_id', user.id).eq('week_start', currentWeek).maybeSingle(),
    supabase.from('family_challenges').select('id, household_id, created_by, title, description, category, target, starts_on, ends_on, created_at').eq('household_id', membership.household_id).gte('ends_on', today()).order('created_at'),
    supabase.from('daily_intentions').select('id, intention, reason, evening_note').eq('user_id', user.id).eq('intended_on', today()).maybeSingle(),
    supabase.from('family_moments').select('id, household_id, created_by, title, description, kind, scheduled_for, status, created_at').eq('household_id', membership.household_id).order('scheduled_for', { ascending: true, nullsFirst: false }).limit(30),
    supabase.from('family_memories').select('id, household_id, moment_id, created_by, caption, created_at').eq('household_id', membership.household_id).order('created_at', { ascending: false }).limit(30),
    supabase.from('family_asks').select('id, household_id, created_by, title, description, status, claimed_by, claimed_at, completed_at, thanked_by, thanked_at, created_at').eq('household_id', membership.household_id).order('created_at', { ascending: false }).limit(50),
    supabase.from('family_garden_entries').select('id, household_id, created_by, kind, created_at').eq('household_id', membership.household_id).gte('created_at', `${currentWeek}T00:00:00.000Z`).order('created_at', { ascending: false }).limit(100),
    supabase.from('family_weekly_choices').select('id, household_id, created_by, week_start, title, target, created_at').eq('household_id', membership.household_id).eq('week_start', currentWeek).maybeSingle(),
    supabase.from('family_warmth_events').select('id, household_id, created_by, kind, message, created_at').eq('household_id', membership.household_id).gte('created_at', `${currentWeek}T00:00:00.000Z`).order('created_at', { ascending: false }).limit(30),
    supabase.from('profiles').select('id, display_name'),
  ])
  if (householdError || checkInError || goalsError || reflectionError || challengesError || intentionError || momentsError || memoriesError || asksError || gardenError || weeklyChoiceError || warmthEventError || profilesError) throw householdError || checkInError || goalsError || reflectionError || challengesError || intentionError || momentsError || memoriesError || asksError || gardenError || weeklyChoiceError || warmthEventError || profilesError

  const goalIds = goals.map(({ id }) => id); const challengeIds = challenges.map(({ id }) => id); const momentIds = moments.map(({ id }) => id)
  const [{ data: goalLogs, error: goalLogError }, { data: participants, error: participantError }, { data: challengeLogs, error: challengeLogError }, { data: momentParticipants, error: momentParticipantError }] = await Promise.all([
    goalIds.length ? supabase.from('goal_progress_logs').select('goal_id, user_id, amount').in('goal_id', goalIds) : Promise.resolve({ data: [], error: null }),
    challengeIds.length ? supabase.from('family_challenge_participants').select('challenge_id, user_id, status').in('challenge_id', challengeIds) : Promise.resolve({ data: [], error: null }),
    challengeIds.length ? supabase.from('family_challenge_logs').select('challenge_id, user_id, amount').in('challenge_id', challengeIds) : Promise.resolve({ data: [], error: null }),
    momentIds.length ? supabase.from('family_moment_participants').select('moment_id, user_id, status').in('moment_id', momentIds) : Promise.resolve({ data: [], error: null }),
  ])
  if (goalLogError || participantError || challengeLogError || momentParticipantError) throw goalLogError || participantError || challengeLogError || momentParticipantError
  const enrichedGoals = enrichGoals(goals, goalLogs, user.id); const enrichedChallenges = enrichChallenges(challenges, participants, challengeLogs, user.id); const score = calculateHarmonyScore(enrichedGoals, enrichedChallenges); const profileNames = Object.fromEntries(profiles.map((person) => [person.id, person.display_name]))
  return { profile, membership, household, checkIns: Object.fromEntries(checkIns.map(({ kind }) => [kind, true])), goals: enrichedGoals, challenges: enrichedChallenges, moments: enrichMoments(moments, momentParticipants, user.id), memories: memories.map((memory) => ({ ...memory, authorName: profileNames[memory.created_by] || null })), asks: asks.map((ask) => ({ ...ask, requesterName: profileNames[ask.created_by] || null, claimantName: profileNames[ask.claimed_by] || null, thankedByName: profileNames[ask.thanked_by] || null })), gardenEntries, weeklyChoice, warmthEvents: warmthEvents.map((event) => ({ ...event, authorName: profileNames[event.created_by] || null })), dailyIntention, reflection, score, achievements: unlockAchievements(enrichedGoals, enrichedChallenges, score) }
}

export async function createHousehold(name, userId) { const { error } = await supabase.from('households').insert({ name: name.trim(), created_by: userId }); if (error) throw error }
export async function toggleCheckIn({ householdId, userId, kind, completed }) { const query = completed ? supabase.from('check_ins').delete().eq('household_id', householdId).eq('user_id', userId).eq('kind', kind).eq('completed_on', today()) : supabase.from('check_ins').insert({ household_id: householdId, user_id: userId, kind, completed_on: today() }); const { error } = await query; if (error) throw error; return !completed }
export async function addExistingMember(householdId, email) { const { error } = await supabase.rpc('add_existing_household_member', { target_household_id: householdId, target_email: email.trim() }); if (error) throw error }
export async function updateProfileLocale(locale) { const { error } = await supabase.from('profiles').update({ locale }).eq('id', (await supabase.auth.getUser()).data.user.id); if (error) throw error }
export async function createWeeklyGoal({ householdId, userId, title, description, visibility, target, category = 'growth', presetKey = null }) { const { data, error } = await supabase.from('weekly_goals').insert({ household_id: householdId, created_by: userId, title: title.trim(), description: description.trim() || null, visibility, target: Number(target), category, preset_key: presetKey, week_start: weekStart() }).select('id, household_id, created_by, visibility, title, description, target, week_start, created_at, category, preset_key').single(); if (error) throw error; return { ...data, progress: 0, myProgress: 0 } }
export async function logGoalProgress({ goalId, userId, amount }) { const { error } = await supabase.from('goal_progress_logs').insert({ goal_id: goalId, user_id: userId, amount: Number(amount) }); if (error) throw error }
export async function saveWeeklyReflection({ householdId, userId, values }) { const { data, error } = await supabase.from('weekly_reflections').upsert({ household_id: householdId, user_id: userId, week_start: weekStart(), win: values.win.trim() || null, obstacle: values.obstacle.trim() || null, next_focus: values.nextFocus.trim() || null, small_reward: values.smallReward.trim() || null, updated_at: new Date().toISOString() }, { onConflict: 'user_id,week_start' }).select('id, win, obstacle, next_focus, small_reward').single(); if (error) throw error; return data }
export async function createFamilyChallenge({ householdId, userId, title, description, category, target, duration }) { const endsOn = new Date(); endsOn.setDate(endsOn.getDate() + Number(duration)); const endDate = `${endsOn.getFullYear()}-${String(endsOn.getMonth() + 1).padStart(2, '0')}-${String(endsOn.getDate()).padStart(2, '0')}`; const { data, error } = await supabase.from('family_challenges').insert({ household_id: householdId, created_by: userId, title: title.trim(), description: description.trim() || null, category, target: Number(target), ends_on: endDate }).select('id, household_id, created_by, title, description, category, target, starts_on, ends_on, created_at').single(); if (error) throw error; return { ...data, progress: 0, participantCount: 1, joined: true } }
export async function joinFamilyChallenge(challengeId, userId) { const { error } = await supabase.from('family_challenge_participants').upsert({ challenge_id: challengeId, user_id: userId, status: 'accepted' }); if (error) throw error }
export async function logChallengeProgress({ challengeId, userId, amount }) { const { error } = await supabase.from('family_challenge_logs').insert({ challenge_id: challengeId, user_id: userId, amount: Number(amount) }); if (error) throw error }

export async function saveDailyIntention({ householdId, userId, values }) { const { data, error } = await supabase.from('daily_intentions').upsert({ household_id: householdId, user_id: userId, intended_on: today(), intention: values.intention.trim() || null, reason: values.reason.trim() || null, evening_note: values.eveningNote.trim() || null, updated_at: new Date().toISOString() }, { onConflict: 'user_id,intended_on' }).select('id, intention, reason, evening_note').single(); if (error) throw error; return data }
export async function createFamilyMoment({ householdId, userId, title, description, kind, scheduledFor }) { const { data, error } = await supabase.from('family_moments').insert({ household_id: householdId, created_by: userId, title: title.trim(), description: description.trim() || null, kind, scheduled_for: scheduledFor || null }).select('id, household_id, created_by, title, description, kind, scheduled_for, status, created_at').single(); if (error) throw error; return { ...data, participantCount: 1, responseCount: 1, myResponse: 'going' } }
export async function updateFamilyMoment({ momentId, title, description, kind, scheduledFor }) { const { data, error } = await supabase.from('family_moments').update({ title: title.trim(), description: description.trim() || null, kind, scheduled_for: scheduledFor || null }).eq('id', momentId).select('id, household_id, created_by, title, description, kind, scheduled_for, status, created_at').single(); if (error) throw error; return data }
export async function setFamilyMomentStatus(momentId, status) { const { data, error } = await supabase.from('family_moments').update({ status }).eq('id', momentId).select('id, household_id, created_by, title, description, kind, scheduled_for, status, created_at').single(); if (error) throw error; return data }
export async function respondToFamilyMoment(momentId, userId, status) { const { error } = await supabase.from('family_moment_participants').upsert({ moment_id: momentId, user_id: userId, status }); if (error) throw error }
export async function joinFamilyMoment(momentId, userId) { return respondToFamilyMoment(momentId, userId, 'going') }

export async function createFamilyMemory({ householdId, momentId, userId, caption }) { const { data, error } = await supabase.from('family_memories').insert({ household_id: householdId, moment_id: momentId, created_by: userId, caption: caption.trim() }).select('id, household_id, moment_id, created_by, caption, created_at').single(); if (error) throw error; return data }
export async function createFamilyAsk({ householdId, userId, title, description }) { const { data, error } = await supabase.from('family_asks').insert({ household_id: householdId, created_by: userId, title: title.trim(), description: description.trim() || null }).select('id, household_id, created_by, title, description, status, claimed_by, claimed_at, completed_at, thanked_by, thanked_at, created_at').single(); if (error) throw error; return data }
export async function claimFamilyAsk(askId, userId) { const { data, error } = await supabase.from('family_asks').update({ status: 'claimed', claimed_by: userId, claimed_at: new Date().toISOString() }).eq('id', askId).eq('status', 'open').is('claimed_by', null).select('id, household_id, created_by, title, description, status, claimed_by, claimed_at, completed_at, thanked_by, thanked_at, created_at').single(); if (error) throw error; return data }
export async function completeFamilyAsk(askId, userId) { const { data, error } = await supabase.from('family_asks').update({ status: 'completed', completed_at: new Date().toISOString() }).eq('id', askId).eq('claimed_by', userId).eq('status', 'claimed').select('id, household_id, created_by, title, description, status, claimed_by, claimed_at, completed_at, thanked_by, thanked_at, created_at').single(); if (error) throw error; return data }
export async function thankFamilyAsk(askId, userId) { const { data, error } = await supabase.from('family_asks').update({ thanked_by: userId, thanked_at: new Date().toISOString() }).eq('id', askId).eq('created_by', userId).eq('status', 'completed').is('thanked_by', null).select('id, household_id, created_by, title, description, status, claimed_by, claimed_at, completed_at, thanked_by, thanked_at, created_at').single(); if (error) throw error; return data }
export async function cancelFamilyAsk(askId, userId) { const { data, error } = await supabase.from('family_asks').update({ status: 'cancelled' }).eq('id', askId).eq('created_by', userId).in('status', ['open', 'claimed']).select('id, household_id, created_by, title, description, status, claimed_by, claimed_at, completed_at, thanked_by, thanked_at, created_at').single(); if (error) throw error; return data }
export async function logGardenEntry({ householdId, userId, kind }) { const { data, error } = await supabase.from('family_garden_entries').insert({ household_id: householdId, created_by: userId, kind }).select('id, household_id, created_by, kind, created_at').single(); if (error) throw error; return data }
export async function saveWeeklyChoice({ householdId, userId, title, target }) { const { data, error } = await supabase.from('family_weekly_choices').upsert({ household_id: householdId, week_start: weekStart(), created_by: userId, title: title.trim(), target: Number(target) }, { onConflict: 'household_id,week_start' }).select('id, household_id, created_by, week_start, title, target, created_at').single(); if (error) throw error; return data }
export async function createWarmthEvent({ householdId, userId, kind, message }) { const { data, error } = await supabase.from('family_warmth_events').insert({ household_id: householdId, created_by: userId, kind, message: message.trim() || null }).select('id, household_id, created_by, kind, message, created_at').single(); if (error) throw error; return data }
